### PR TITLE
fix epg

### PR DESCRIPTION
**Pull request by dl1ch**
fix epg character set and add xml_declaration

### CODE REVIEW

**Comment by Chris230291** [comment]
What does this change fix? Is the declaration part just good practice or is it required by some clients?
I think I needed to use Unicode so that some Asian characters worked.

**Comment by dl1ch** [comment]
I really don't know about the good practices of creating or using XML files, but the EPG wasn't parsed correctly (not working at all) by Kodi. This was the fix but I assumed it would also help other clients...

**Comment by Chris230291** [comment]
Was it the  xml_declaration or the change from Unicode or both that fixed it?
I'm sure I ran into problems with UTF-8. A google of the error pointed me to Unicode.

**Comment by dl1ch** [comment]
The XML declaration was enough. I set to UTF-8 because it's the XML's default value (so probably most clients use it), but with the declaration also Unicode can be used for more languages...

**Comment by Chris230291** [comment]
OK thanks. I will just add the declaration for now. Thanks for the help.

**Pull request closed without merging**
