### PR TITLE
Added some useful features

### PR DESCRIPTION
**Pull request by jojo141185**
I have added some useful features to this project that I would like to share with you. 

These changes include:
- New streaming method (direct buffer).
- Detection of the cause of streaming interruptions e.g. by simultaneous use of a Mac address 
- EPG time offset (individual setting for each portal)
- Collecting statistics for Mac addresses (playtime, error rate)
- Project structure reorganized / restructured

**Important note:** The structure of the configuration file has changed. Please create a backup before first use.

### CODE REVIEW

**Review by Chris230291 — COMMENTED** [review]
Thanks.
I did a quick look and it seems you fixed some issues that I didnt know how to and added some features that I was already working on.
I will test it and see if I can merge it (manually) with what I have been working on.

**Comment by Chris230291** [comment]
I have tested it and everything seems to be OK.
Its looks like you havent finished yet but since it doesnt seem to break anything i'll go ahead and merge it as soon as i figure out how to.

**Comment by jojo141185** [comment]
Thanks for testing my PR and your positive feedback!
I am not a professional programmer either. In my spare time I try to support some interesting projects, like STB-Proxy is, to improve my programming skills a bit.
It would be great if you could implement the advanced features from this PR in your next release. 
Thanks for your efforts :-)

**Comment by Chris230291** [comment]
Please be paitiant.
I am adding the ability to add xtream codes and m3us from url and file in the future.
Because of this it means a major rework.
I am incorperating some of the changes you made manually.
You will see what I mean once I release it.

**Comment by Chris230291** [comment]
I just added a new test branch that shows you what I was thinking.

**Comment by Chris230291** [comment]
I just created a new branch that gives you an idea of what I was thinking.
Perhaps they should be seperate apps instead of combined?
I'm undecided.

**Comment by jojo141185** [comment]
Hello Chris,
I'm sorry that I'm only getting back to you now. I've only just found the time to take a look at your new test branch. It looks great! I particularly like the idea of integrating xtream code and m3u in the future, as I haven't found an app yet that combines everything under one roof.
The following projects are currently my favorites in this regard:
- https://github.com/pierre-emmanuelJ/iptv-proxy/: An xtream proxy, unfortunately without filter function and without proxy/cache of logos & icons
- https://github.com/euzu/m3u-filter: Good m3u filter that also works with very large lists

You can link the tools hierarchically to combine their functions.

While testing your branch, I unfortunately noticed that files (e.g. stb.py) and some elementary functions (getSettings, getPortals, savePortals, ...) are missing. Have you made any progress here?

If I can support you in testing, please let me know.

**Comment by jojo141185** [comment]
Hello Chris,
I wanted to ask if you are developing any more functions here? It has been relatively quiet recently. 
The implementation in your test branch looked very promising. Maybe there will be an update here that we can build on. That would be really great!

**Pull request merged**
