### PR TITLE
Wrote a requirements.txt

### LINKED ISSUE #5: TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
Previous script was working fine. New script gives this error while trying to run locally (not docker).

`Traceback (most recent call last):
  File "app.py", line 33, in <module>
    retries = Retry(total=5, backoff_factor=0.2, status_forcelist=[500, 502, 503, 504], allowed_m
ods=frozenset(['GET', 'POST']))
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'`

### PR DESCRIPTION
**Pull request by kettenbach-it**
Closes #5

### CODE REVIEW

**Comment by Chris230291** [comment]
There is a whole bunch of stuff in there that isn't needed.
I did run the freeze command when you said so but it appeared to list every pip package I had installed ever.
I think it only works if you use virtual environments.

**Comment by Chris230291** [comment]
I just set up a virtual environment, installed the packages I listed in the readme and then 'pip list' gives...

```
(venv) Z:\Containers\Dockerfiles\stbproxy>pip list
Package            Version
------------------ ---------
aiofiles           0.7.0
asgiref            3.4.1
certifi            2021.5.30
charset-normalizer 2.0.4
click              8.0.1
colorama           0.4.4
fastapi            0.68.1
h11                0.12.0
idna               3.2
Jinja2             3.0.1
MarkupSafe         2.0.1
pip                19.2.3
pydantic           1.8.2
python-multipart   0.0.5
requests           2.26.0
setuptools         41.2.0
six                1.16.0
starlette          0.14.2
typing-extensions  3.10.0.2
urllib3            1.26.6
uvicorn            0.15.0
```

**Comment by kettenbach-it** [comment]
Oh, yes. 
You definitely need a virtualenv! 
Without it, dependency management is not possible. With it, the  dependencies are separated from the systems dependences.

If you accept this PR, there will be the requirements.txt in the repo that everyone who uses a virtual env can use

**Comment by Chris230291** [comment]
Did you see my last comment? How come our lists are very different?

**Comment by kettenbach-it** [comment]
The comments  have overlapped.

They are different, since I installed "pytest" and its dependencies. pytest is need for the tests that I'm working on

**Comment by Chris230291** [comment]
Ok that makes sense. I thought I had done something wrong. Do you think we should include pytest also?

**Comment by kettenbach-it** [comment]
If you accept this Pull-Request, then everything needed for the latest version will be in requirements.txt.

If you installed something with pip (in your virtualenv!), then update requirements.txt with "pip freeze > requirements.txt".
That is the usual workflow four working together on Python projects

**Pull request merged**
